import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import Buycoffee from "../components/Buycoffee";

export default function Home() {
  const injected = new InjectedConnector();
  const { activate, active, account, library: provider } = useWeb3React();

  async function connect() {
    try {
      await activate(injected);
    } catch (e) {
      console.log(e);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy Emmanuel a coffee!</h1>
        <br />
        {active ? (
          <>
            <Buycoffee active={active} account={account} provider={provider} />
          </>
        ) : (
          <>
            <button onClick={() => connect()}>connect your wallet</button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/emmanuelkiranr"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by @emmanuelkiranr
        </a>
      </footer>
    </div>
  );
}
